// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyDz7oQ5O5oloVtyjYdJy09OULtatV-NwoU",
    authDomain: "quote-generator-e1376.firebaseapp.com",
    projectId: "quote-generator-e1376",
    storageBucket: "quote-generator-e1376.firebasestorage.app",
    messagingSenderId: "130179725079",
    appId: "1:130179725079:web:579d7f10e4986580a16952",
    measurementId: "G-Z7K5FS47C3"
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClcQ4SFsDfm2nmOIdxYc5TWd0_NmzoFsQ',
    appId: '1:130179725079:android:481eb5d54e810c2da16952',
    messagingSenderId: '130179725079',
    projectId: 'quote-generator-e1376',
    storageBucket: 'quote-generator-e1376.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADezSSSAAYSbva-2Lx0Td4M0lB41e5Ogc',
    appId: '1:130179725079:ios:f1e95ad5889201f0a16952',
    messagingSenderId: '130179725079',
    projectId: 'quote-generator-e1376',
    storageBucket: 'quote-generator-e1376.firebasestorage.app',
    iosBundleId: 'com.example.quoteApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADezSSSAAYSbva-2Lx0Td4M0lB41e5Ogc',
    appId: '1:130179725079:ios:f1e95ad5889201f0a16952',
    messagingSenderId: '130179725079',
    projectId: 'quote-generator-e1376',
    storageBucket: 'quote-generator-e1376.firebasestorage.app',
    iosBundleId: 'com.example.quoteApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDz7oQ5O5oloVtyjYdJy09OULtatV-NwoU',
    appId: '1:130179725079:web:553833d5ee732b40a16952',
    messagingSenderId: '130179725079',
    projectId: 'quote-generator-e1376',
    authDomain: 'quote-generator-e1376.firebaseapp.com',
    storageBucket: 'quote-generator-e1376.firebasestorage.app',
    measurementId: 'G-Q3F6J39EEP',
  );
}
